#!/usr/bin/env ansible-playbook
---
- name: setup an ansible development environment
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - robertdebock.development_environment.bootstrap
    - robertdebock.development_environment.update
    - robertdebock.development_environment.fail2ban
    - robertdebock.development_environment.common
    - robertdebock.development_environment.buildtools
    - robertdebock.development_environment.epel
    - robertdebock.development_environment.python_pip
    - robertdebock.development_environment.docker
    - robertdebock.development_environment.users
    - robertdebock.development_environment.postfix
    - robertdebock.development_environment.vagrant
    - robertdebock.development_environment.investigate
    - robertdebock.development_environment.ansible
    - robertdebock.development_environment.ansible_lint
    - molecule
    - ara
    - robertdebock.development_environment.ruby
    - robertdebock.development_environment.travis
    - git
    - robertdebock.development_environment.atom
